name: Build and Release Electron App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-slim, windows-2022, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Get version
        id: get_version
        run: |
          if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS" ]]; then
            echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            $version = node -p "require('./package.json').version"
            echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          fi
        shell: bash

      - name: Build Electron
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then npm run electron:pack:linux -- --publish always; fi
          if [[ "$RUNNER_OS" == "Windows" ]]; then npm run electron:pack:win -- --publish always; fi
          if [[ "$RUNNER_OS" == "macOS" ]]; then npm run electron:pack:mac -- --publish always; fi
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist-electron/**
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}